# Generated by Django 4.0.5 on 2024-11-02 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('visualizar_catalogo', 'add_vehiculo_model')]},
        ),
    ]
